/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var ResultReply_pb = require('./ResultReply_pb.js');
var EmptyRequest_pb = require('./EmptyRequest_pb.js');
goog.exportSymbol('proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo', null, global);
goog.exportSymbol('proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.displayName = 'proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.toObject = function(opt_includeInstance) {
  return proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    atomiccounterinfo: (f = msg.getAtomiccounterinfo()) && proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.toObject(includeInstance, f),
    resultreply: (f = msg.getResultreply()) && ResultReply_pb.ResultReply.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply;
  return proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo;
      reader.readMessage(value,proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.deserializeBinaryFromReader);
      msg.setAtomiccounterinfo(value);
      break;
    case 2:
      var value = new ResultReply_pb.ResultReply;
      reader.readMessage(value,ResultReply_pb.ResultReply.deserializeBinaryFromReader);
      msg.setResultreply(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAtomiccounterinfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.serializeBinaryToWriter
    );
  }
  f = message.getResultreply();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      ResultReply_pb.ResultReply.serializeBinaryToWriter
    );
  }
};


/**
 * optional AtomicCounterInfo AtomicCounterInfo = 1;
 * @return {?proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.getAtomiccounterinfo = function() {
  return /** @type{?proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo} */ (
    jspb.Message.getWrapperField(this, proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo, 1));
};


/** @param {?proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo|undefined} value */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.setAtomiccounterinfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.clearAtomiccounterinfo = function() {
  this.setAtomiccounterinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.hasAtomiccounterinfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional JT808.GrpcDashbord.ServiceGrpcBase.ResultReply ResultReply = 2;
 * @return {?proto.JT808.GrpcDashbord.ServiceGrpcBase.ResultReply}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.getResultreply = function() {
  return /** @type{?proto.JT808.GrpcDashbord.ServiceGrpcBase.ResultReply} */ (
    jspb.Message.getWrapperField(this, ResultReply_pb.ResultReply, 2));
};


/** @param {?proto.JT808.GrpcDashbord.ServiceGrpcBase.ResultReply|undefined} value */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.setResultreply = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.clearResultreply = function() {
  this.setResultreply(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterReply.prototype.hasResultreply = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.displayName = 'proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgsuccesscount: jspb.Message.getFieldWithDefault(msg, 1, 0),
    msgfailcount: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo;
  return proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMsgsuccesscount(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMsgfailcount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMsgsuccesscount();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMsgfailcount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 MsgSuccessCount = 1;
 * @return {number}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.prototype.getMsgsuccesscount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.prototype.setMsgsuccesscount = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 MsgFailCount = 2;
 * @return {number}
 */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.prototype.getMsgfailcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.JT808.GrpcDashbord.AtomicCounterGrpcService.AtomicCounterInfo.prototype.setMsgfailcount = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.JT808.GrpcDashbord.AtomicCounterGrpcService);
