// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: JT808UnificationSendService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace JT808.GrpcDashbord.AtomicCounterGrpcService {
  public static partial class UnificationSendService
  {
    static readonly string __ServiceName = "JT808.GrpcDashbord.AtomicCounterGrpcService.UnificationSendService";

    static readonly grpc::Marshaller<global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest> __Marshaller_JT808_GrpcDashbord_AtomicCounterGrpcService_SendTextRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReply> __Marshaller_JT808_GrpcDashbord_ServiceGrpcBase_ResultReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReply.Parser.ParseFrom);

    static readonly grpc::Method<global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest, global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReply> __Method_SendText = new grpc::Method<global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest, global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendText",
        __Marshaller_JT808_GrpcDashbord_AtomicCounterGrpcService_SendTextRequest,
        __Marshaller_JT808_GrpcDashbord_ServiceGrpcBase_ResultReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::JT808.GrpcDashbord.AtomicCounterGrpcService.JT808UnificationSendServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UnificationSendService</summary>
    public abstract partial class UnificationSendServiceBase
    {
      /// <summary>
      /// 文本信息下发
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReply> SendText(global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UnificationSendService</summary>
    public partial class UnificationSendServiceClient : grpc::ClientBase<UnificationSendServiceClient>
    {
      /// <summary>Creates a new client for UnificationSendService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UnificationSendServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UnificationSendService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UnificationSendServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UnificationSendServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UnificationSendServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// 文本信息下发
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReply SendText(global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendText(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 文本信息下发
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReply SendText(global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendText, null, options, request);
      }
      /// <summary>
      /// 文本信息下发
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReply> SendTextAsync(global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendTextAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 文本信息下发
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReply> SendTextAsync(global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendText, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UnificationSendServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UnificationSendServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UnificationSendServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SendText, serviceImpl.SendText).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UnificationSendServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SendText, serviceImpl.SendText);
    }

  }
}
#endregion
