// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: JT808UnificationSendService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace JT808.GrpcDashbord.AtomicCounterGrpcService {

  /// <summary>Holder for reflection information generated from JT808UnificationSendService.proto</summary>
  public static partial class JT808UnificationSendServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for JT808UnificationSendService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static JT808UnificationSendServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFKVDgwOFVuaWZpY2F0aW9uU2VuZFNlcnZpY2UucHJvdG8SK0pUODA4Lkdy",
            "cGNEYXNoYm9yZC5BdG9taWNDb3VudGVyR3JwY1NlcnZpY2UaEVJlc3VsdFJl",
            "cGx5LnByb3RvIjsKD1NlbmRUZXh0UmVxdWVzdBIXCg9UZXJtaW5hbFBob25l",
            "Tm8YASABKAkSDwoHQ29udGVudBgCIAEoCTKVAQoWVW5pZmljYXRpb25TZW5k",
            "U2VydmljZRJ7CghTZW5kVGV4dBI8LkpUODA4LkdycGNEYXNoYm9yZC5BdG9t",
            "aWNDb3VudGVyR3JwY1NlcnZpY2UuU2VuZFRleHRSZXF1ZXN0Gi8uSlQ4MDgu",
            "R3JwY0Rhc2hib3JkLlNlcnZpY2VHcnBjQmFzZS5SZXN1bHRSZXBseSIAYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::JT808.GrpcDashbord.ServiceGrpcBase.ResultReplyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest), global::JT808.GrpcDashbord.AtomicCounterGrpcService.SendTextRequest.Parser, new[]{ "TerminalPhoneNo", "Content" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///下发文本信息参数
  /// </summary>
  public sealed partial class SendTextRequest : pb::IMessage<SendTextRequest> {
    private static readonly pb::MessageParser<SendTextRequest> _parser = new pb::MessageParser<SendTextRequest>(() => new SendTextRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SendTextRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::JT808.GrpcDashbord.AtomicCounterGrpcService.JT808UnificationSendServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendTextRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendTextRequest(SendTextRequest other) : this() {
      terminalPhoneNo_ = other.terminalPhoneNo_;
      content_ = other.content_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendTextRequest Clone() {
      return new SendTextRequest(this);
    }

    /// <summary>Field number for the "TerminalPhoneNo" field.</summary>
    public const int TerminalPhoneNoFieldNumber = 1;
    private string terminalPhoneNo_ = "";
    /// <summary>
    ///终端手机号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TerminalPhoneNo {
      get { return terminalPhoneNo_; }
      set {
        terminalPhoneNo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Content" field.</summary>
    public const int ContentFieldNumber = 2;
    private string content_ = "";
    /// <summary>
    ///内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SendTextRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SendTextRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TerminalPhoneNo != other.TerminalPhoneNo) return false;
      if (Content != other.Content) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TerminalPhoneNo.Length != 0) hash ^= TerminalPhoneNo.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TerminalPhoneNo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TerminalPhoneNo);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TerminalPhoneNo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TerminalPhoneNo);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SendTextRequest other) {
      if (other == null) {
        return;
      }
      if (other.TerminalPhoneNo.Length != 0) {
        TerminalPhoneNo = other.TerminalPhoneNo;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TerminalPhoneNo = input.ReadString();
            break;
          }
          case 18: {
            Content = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
