// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: JT808SessionService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace JT808.GrpcDashbord.SessionGrpcService {
  public static partial class SessionService
  {
    static readonly string __ServiceName = "JT808.GrpcDashbord.SessionGrpcService.SessionService";

    static readonly grpc::Marshaller<global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest> __Marshaller_JT808_GrpcDashbord_ServiceGrpcBase_EmptyRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::JT808.GrpcDashbord.SessionGrpcService.TcpSessionReply> __Marshaller_JT808_GrpcDashbord_SessionGrpcService_TcpSessionReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::JT808.GrpcDashbord.SessionGrpcService.TcpSessionReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::JT808.GrpcDashbord.SessionGrpcService.UdpSessionReply> __Marshaller_JT808_GrpcDashbord_SessionGrpcService_UdpSessionReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::JT808.GrpcDashbord.SessionGrpcService.UdpSessionReply.Parser.ParseFrom);

    static readonly grpc::Method<global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest, global::JT808.GrpcDashbord.SessionGrpcService.TcpSessionReply> __Method_GetTcpSessionAll = new grpc::Method<global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest, global::JT808.GrpcDashbord.SessionGrpcService.TcpSessionReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTcpSessionAll",
        __Marshaller_JT808_GrpcDashbord_ServiceGrpcBase_EmptyRequest,
        __Marshaller_JT808_GrpcDashbord_SessionGrpcService_TcpSessionReply);

    static readonly grpc::Method<global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest, global::JT808.GrpcDashbord.SessionGrpcService.UdpSessionReply> __Method_GetUdpSessionAll = new grpc::Method<global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest, global::JT808.GrpcDashbord.SessionGrpcService.UdpSessionReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUdpSessionAll",
        __Marshaller_JT808_GrpcDashbord_ServiceGrpcBase_EmptyRequest,
        __Marshaller_JT808_GrpcDashbord_SessionGrpcService_UdpSessionReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::JT808.GrpcDashbord.SessionGrpcService.JT808SessionServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SessionService</summary>
    public abstract partial class SessionServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::JT808.GrpcDashbord.SessionGrpcService.TcpSessionReply> GetTcpSessionAll(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::JT808.GrpcDashbord.SessionGrpcService.UdpSessionReply> GetUdpSessionAll(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SessionService</summary>
    public partial class SessionServiceClient : grpc::ClientBase<SessionServiceClient>
    {
      /// <summary>Creates a new client for SessionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SessionServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SessionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SessionServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SessionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SessionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::JT808.GrpcDashbord.SessionGrpcService.TcpSessionReply GetTcpSessionAll(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTcpSessionAll(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::JT808.GrpcDashbord.SessionGrpcService.TcpSessionReply GetTcpSessionAll(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTcpSessionAll, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::JT808.GrpcDashbord.SessionGrpcService.TcpSessionReply> GetTcpSessionAllAsync(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTcpSessionAllAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::JT808.GrpcDashbord.SessionGrpcService.TcpSessionReply> GetTcpSessionAllAsync(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTcpSessionAll, null, options, request);
      }
      public virtual global::JT808.GrpcDashbord.SessionGrpcService.UdpSessionReply GetUdpSessionAll(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUdpSessionAll(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::JT808.GrpcDashbord.SessionGrpcService.UdpSessionReply GetUdpSessionAll(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUdpSessionAll, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::JT808.GrpcDashbord.SessionGrpcService.UdpSessionReply> GetUdpSessionAllAsync(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUdpSessionAllAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::JT808.GrpcDashbord.SessionGrpcService.UdpSessionReply> GetUdpSessionAllAsync(global::JT808.GrpcDashbord.ServiceGrpcBase.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUdpSessionAll, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SessionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SessionServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SessionServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetTcpSessionAll, serviceImpl.GetTcpSessionAll)
          .AddMethod(__Method_GetUdpSessionAll, serviceImpl.GetUdpSessionAll).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SessionServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetTcpSessionAll, serviceImpl.GetTcpSessionAll);
      serviceBinder.AddMethod(__Method_GetUdpSessionAll, serviceImpl.GetUdpSessionAll);
    }

  }
}
#endregion
